accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
	path('register/', views.register, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('', include('main.urls', namespace = 'main')),
]

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('logout/', auth_views.LogoutView.as_view(template_name='main/logout.html'), name = 'logout' ),
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name = 'login' ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email',]
    address = models.CharField(max_length= 250)

main/models.py
from django.db import models
from django.utils.translation import ugettext as _


class BlogCategory(models.Model):
    title = models.CharField(
            max_length=256,
            verbose_name = _('Title: '),
            unique=True,
            blank= False,
            null= False
        )

    class Meta:
        verbose_name = _('Blog_Categoty')
        verbose_name_plural = _('Blog_Categories')

    def __str__(self):
        return self.title


class Blog(models.Model):
    title = models.CharField(
            max_length = 256,
            verbose_name = _('Title: '),
            unique=True,
            blank=False,
            null=False,
        )

    slug = models.SlugField(
            max_length=256,
            verbose_name = _('Slug :'),
            unique = True,
            blank = False,
            null = False
        )

forms/accounts.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from accounts.models import User

class EmailRequiredMixin(object):
    def __init__(self, *args, **kwargs):
        super(EmailRequiredMixin, self).__init__(*args, **kwargs)
        # make user email field required
        self.fields['email'].required = True
        self.fields['username'].help_text = "Read only."


class UsernameDisableMixin(object):
	def __init__(self, *args, **kwargs):
		super(UsernameDisableMixin, self).__init__(*args, **kwargs)
		self.fields['username'].disabled = True


class UserCreationForm(UserCreationForm):
	def __init__(self, *args, **kwargs):
		super(UserCreationForm, self).__init__(*args, **kwargs)

		self.fields['email'].required = True
		self.fields['first_name']. required = True
		self.fields['last_name'].required = True

	class Meta:
		model = User
		# tinanggal ko ung password 1 and 2 kasi nagdodoble ng textbox sa frontend
		fields = [
			 'first_name', 'last_name', 'email','username',
		]


class UserChangeForm(EmailRequiredMixin, UsernameDisableMixin, UserChangeForm):
	def __init__(self, *args, **kwargs):
		super(UserChangeForm, self).__init__(*args, **kwargs)
		# make some attributes field required
		self.fields['first_name'].required = True
		self.fields['last_name'].required = True\

	class Meta:
		model = User
		fields = []

accounts/views.py
from django.shortcuts import render, redirect
from forms import accounts
from django.contrib import messages


def register(request):
    if request.method == "POST":
        form = accounts.UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            #capitalize() or .title() will work
            messages.success(request, f'Welcome, {first_name.capitalize()} {last_name.capitalize()}!')
            return redirect('register')
    if request.method == "GET":
        form = accounts.UserCreationForm()

    context = {
		'form': form,
	}
    return render(request, 'accounts/register.html',context)

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'main/home.html')

templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}

{% block nav %}{% endblock %}

{% block content %}
  <div class="container d-fixed h-100 align-items-center">
    <div class="mx-auto">
        <div class="row">
            <div class="col">
            </div>
            <div class="col-sm-5 " style='margin-top:7rem'>
                <form method="POST">
                    {%csrf_token%}
                    <p><small class="text-muted">insert cvs logo here</small></p>
                    <fieldset class='form-group'>
                        <legend class= 'border-bottom mb-4' style="text-align: center">Be a Conqueror!</legend>
                        <small class="text-muted">Just a sample legend, not really related to Blog but to CVS Website.</small>
                        <br><br>
                        {{form|crispy}}
                    </fieldset>

                    <br>
                    <div class="form-group">
                        <button class="btn btn-primary" type='submit'>Join Now!</button>
                    </div>
                    <div>
                        <small><a href="#">Forgot your password?</a></small>
                    </div>
                </form>
            </div>
            <div class="col">
            </div>
        </div>
    </div>
  </div>
  <br><br><br><br><br>

<div class="form-floating mb-3">
  <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
  <label for="floatingInput">Email address</label>
</div>
<div class="form-floating">
  <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
  <label for="floatingPassword">Password</label>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>gitpractice | {% block title %}{% endblock %}</title>
  </head>
  <body>

    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'main:home' %}">Practice Website</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">create user function</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}" tabindex="-1" aria-disabled="true">Admin Page</a>
              </li>
            </ul>
          </div>
          <form class="d-flex">
            {% if user.is_authenticated %}
            <a  class="btn btn-outline-dark"  href="{% url 'main:logout' %}">Logout</a>

            {% else %}
              <a class="btn btn-outline-dark" href="{% url 'main:login' %}"> Login</a>
            {% endif %}
          </form>
        </div>
      </nav>
      {% if messages %}
      {% for message in messages %}
      {% if message.tags == 'success' %}
          <div class="alert alert-success" role="alert">{{ message|escape|safe }}</div>
      {% elif message.tags == 'error' %}
          <div class="alert alert-danger" role="alert">{{ message|escape|safe }}</div>
      {% endif %}
      {% endfor %}
      {% endif %}


      {% block content %}

      {% endblock %}
    </div>
    {%block sidebar%}
   
    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/main/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h6>Welcome, {{request.user}}</h6>
    <h3>HI JOSH</h3>
{% endblock %}
{%block sidebar%}
     <ul>TRY</ul>
     <ul>KO</ul>
    {% endblock %}

templates/main/login.html
<form action="action_page.php" method="post">
 
  <div class="container">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
  </div>

  <div class="container" style="background-color:#f1f1f1">
    <button type="button" class="cancelbtn">Cancel</button>
    <span class="psw">Forgot <a href="#">password?</a></span>
  </div>
</form>

templates/main/logout.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    you are now logged out. <a href="{% url 'main:login' %}"> Log in?</a>
{% endblock %}
{%block sidebar%}
<h6>BABYE</h6>
    {% endblock %}